### ISSUE TITLE
Lab0 Startup.m

### ISSUE THREAD

**Issue by khan2018** [sdrforengineers/LabGuides#4]
Hi
I was just browsing through the lab files and Lab 0 has this startup file which adds drivers to the path.
Since I am using Pluto Addon in Matlab, is this driver something different?
sdr = PlutoSDR;
sdr.mode = 'transceive';
sdr.rx_gain = 10;
sdr.rx_gain_mode = 'fast-attack';

So these functions are not recognized ... in Matlab we use sdrtx and sdrrx .
Could you please mention what driver is it pointing to?

Thanks

**Comment by tfcollins** [comment]
Looks like we had some old code related to the drivers before the official ones were available. The example has been updated to use the new classes.

Thanks for reporting.

-Travis
